#!/data/data/com.termux/files/usr/bin/bash
clear
println()
{
	echo
	echo "*****************************"
}

println
echo "        Script by Hax4Us(Lokesh) "
println
echo "    Installing dependencies ( for setup)"
println
apt install dirmngr gnupg-curl -y
clear
println
println
echo "            Adding repository"
println
echo "deb https://termux.net stable main" > ${PREFIX}/etc/apt/sources.list
echo "deb https://termux.xeffyr.ml/ extra main x11" > $PREFIX/etc/apt/sources.list.d/xeffyr.list
println
echo "               Adding key"
apt-key adv --keyserver keys.gnupg.net --recv 9D6D488416B493F0
echo " Key added "
apt update -y
println
echo "   Install dependencies (for wireshark)"
println
apt-get install tigervnc -y
vncserver
println
echo "             setup completed"
println
echo "           Installing wireshark"
println
apt-get install wireshark -y
println
echo "    type -----> wireshark-gtk to start"
println
