#!${PREFIX}/bin/sh
SCRIPT_NAME=$(basename "$0")
METASPLOIT_PATH="${HOME}/metasploit-framework"
# Fix ruby bigdecimal extensions linking error.
case "$(uname -m)" in
	aarch64)
		export LD_PRELOAD="@TERMUX_PREFIX@/lib/ruby/2.6.0/aarch64-linux-android/bigdecimal.so:$LD_PRELOAD"
		;;
	arm*)
		export LD_PRELOAD="@TERMUX_PREFIX@/lib/ruby/2.6.0/arm-linux-androideabi/bigdecimal.so:$LD_PRELOAD"
		;;
	i686)
		export LD_PRELOAD="@TERMUX_PREFIX@/lib/ruby/2.6.0/i686-linux-android/bigdecimal.so:$LD_PRELOAD"
		;;
	x86_64)
		export LD_PRELOAD="@TERMUX_PREFIX@/lib/ruby/2.6.0/x86_64-linux-android/bigdecimal.so:$LD_PRELOAD"
		;;
	*)
		;;
esac
case "$SCRIPT_NAME" in
	msfconsole|msfvenom)
		exec ruby "$METASPLOIT_PATH/$SCRIPT_NAME" "$@"
		;;
	*)
		echo "[!] Unknown Metasploit command '$SCRIPT_NAME'."
		exit 1
		;;
esac
